var messages = [
	["hoy no hay na, más intriga para mañana, no?", "Charles Dickens"],
	["hola q tal, hoy sí hay una curiosidad y es esta: donde estan estos cuadraditos tiene como una imagen de mierda", "Mary Ellen Chase"],
	["dicen que por estás fechas se dicen cosas bonitas y tal pero yo me seguiré cagando en los muertos de rockium", "Norman Vincent Peale"],
	["la madre de bots es una zorra, q no os mientan...", "Hamilton Wright Mabie"],
	["la música me gusta mucho, demasiado diría yo", "Garrison Keillor"],
	["Y AHORA TOCA UN VERANOO SIN TIIIII LA ESTOY PASANDO BIEN NO TE VOY A MENTIR, PERO A VECES TU NOMBRE NO ME DEJA DORMIR", "Eric Sevareid"],
	["quemo los albums muy rápido, pero es lo que hay escucho MUCHA música, por no decir TOODO el día", "Kevin Alan Milne"],
	["quería hacer algo en esta web, mañana sabran que era (no se si lo hice, ando haciendo estos mensajes el 27/11/22 12:15)", "Larry Wilde"],
	["quiero que el último día en vez de poner X te de 1 céntimo, pero UFFF es arriesgao asi q no o si?", "Helen Steiner Rice"],
	["algo que me toque los cojones¿? pues que haya gente que envíe soli en dc por la puta cara, odio los bots, me voy a deshaogar aquí", "Salman Rushdie"],
	["odio que me añadan a grupos de tocsar los huevos con mierdas de amazon hermano q me la pela", "Bing Crosby"],
	["que mas pongo :C", "Peg Bracken"],
	["realmente la primera web mía la de polo1245.com había salido de un video donde (1/2)", "Lemony Snicket"],
	["hacían un bot de dc 24/7, ya que en esa época era la mejor era de discord.js (estoy hablando de discord.js v11) 2/2", "Dr. Seuss"],
	["MEH día 15 creo, y como q no, no¿? mejor mañana", "Lisa Kleypas"],
	["hoy sí, solo voy a decir gracias por estar siguiendo estos días aquí conmigo y eso", "Harlan Miller"],
	["realmente, esta cosa es de github lol, no se hacer tanto cabron, y mira q es fácil pero joder (1/2)", "Freya Stark"],
	["ayer que fue cuando empecé con este proyecto (es decir el 26/11/22) encontré una web que literalmente tenia como 9 años 2/3", "Dale Evans Rogers"],
	["bro que usaba NODE.JS con un archivo HTML es decir el npm start => node index.html 3/3", "Joan Mills"],
	["y bien, recta final, si de verdad llegaron hasta aquí envienme un md de twitter q me haría ilusión", "Dale Evans Rogers"],
	["bueno, que mas pongo, ya no sé, puse toda mi vida (3 días)", "polo1245"],
	["algo que siempre me ha molestado es pq hay tanto hijo de puta tio (2 días)", "Rosie Thomas"],
	["bueno, nada más tengo q decir, hoy sino me equivoco es la cena estas así que bueno, ya solo queda 1 día :D", "Gladys Taber"],
	["¡FELIZ NAVIDAD! Gracias por recorrer estos días conmigo y eso :D", "Polo_1245"]
];